# Generated by Django 5.0 on 2023-12-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Publication_Year', models.IntegerField()),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('Price', models.DecimalField(decimal_places=200, max_digits=200)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookLibrary.authormodel')),
            ],
        ),
    ]
