# Generated by Django 5.0 on 2023-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
